version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=network_metrics
    ports:
      - "9834:8086"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3000
    ports:
      - "9834:3000"
    depends_on:
      - influxdb

  network-monitor:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    depends_on:
      - influxdb
      - grafana

volumes:
  influxdb-data:
  grafana-data:
